config/routes.rb
Rails.application.routes.draw do
  root to: "games#index"
  resources :games
  devise_for :users

  get '/addresses', to: 'addresses#index'
  get '/addresses/new', to: 'addresses#new'
  get '/addresses/:id', to: 'addresses#show', as: "address"
  post '/addresses', to: 'addresses#create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user # One address can have many users, but one user can only have one address
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
  # for adding a picture
  has_one_attached :gamepic

  # conditions some damage, incomplete, good, well looked after, brand new
  # {"some damage" => 1, "incomplete" => 2, "good" => 3, "well looked after" => 4, "brand new" => 5}
  enum condition: {some_damage: 1, incomplete: 2, good: 3, well_looked_after: 4, brand_new: 5}

  # genres sci-fi/fantasy, family, strategy, RPG, worker placement, co-op
  # {"sci-fi/fantasy" => 1, "family" => 2, "strategy" => 3, "RPG" => 4, "worker placement" => 5, "co-op" => 6}
  enum genre: {science_fiction: 1, fantasy: 2, family: 3, strategy: 4, RPG: 5, worker_placement: 6, co_op: 7}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :games
  has_one :address, dependent: :destroy # One address can have many users, but one user can only have one address
  # has_many :users
  accepts_nested_attributes_for :address
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def address
    super || build_address
  end
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
    before_action :set_address, only: %i[ show edit update destroy ]
    before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
    before_action :check_ownership, only: [:show, :edit, :update, :destroy]

    # GET /addresses
    def index
        @addresses = Address.all
    end

    # GET /addresses/1
    def show
        @address = Address.find(params[:id])
    end

    # GET /addresses/new
    def new
        @address = Address.new
    end

    # GET /addresses/1/edit
    def edit
    end

    # POST /games
    def create
        Address.create(street_number: params[:street_number], street_name: params[:street_name], suburb: params[:suburb], state: params[:state], postcode: params[:postcode], user: current_user)
        redirect_to games_path
    end

    # PATCH/PUT /addresses/1
    def update
        respond_to do |format|
        if @address.update(address_params)
            format.html { redirect_to game_url, notice: "Address was successfully updated." }
    
        else
            format.html { render :edit, status: :unprocessable_entity }
            
        end
        end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
        @address = Address.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    # def address_params
    #     params.require(:address).permit(:street_number, :street_name, :suburb, :state, :postcode)
    #   end

    def check_ownership
        if !(current_user.admin? or current_user.id == @address.user_id)
          redirect_to games_url, alert: "You have to be the authorised user or an admin to do this."
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username, address_attributes: [:street_number, :street_name, :suburb, :state, :postcode]])
    end
end

# this will help later when I add the address
    # before_action :configure_permitted_parameters, if: :devise_controller?

    #   protected

    #   def configure_permitted_parameters
    #     devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, address_attributes: [:country, :state, :city, :area, :postal_code]])
    #   end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :check_ownership, only: [:edit, :update, :destroy]

  # GET /games
  def index
    @games = Game.all
  end

  # GET /games/1
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  def create
    # @game = Game.new(game_params, user_id: current_user.user_id)
    @game = Game.new(name: game_params[:name], condition: game_params[:condition], min_player: game_params[:min_player], max_player: game_params[:max_player], price: game_params[:price], description: game_params[:description], genre: game_params[:genre], user: current_user)
    respond_to do |format|
      if @game.save
        format.html { redirect_to game_url(@game), notice: "Game was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to game_url(@game), notice: "Game was successfully updated." }
  
      else
        format.html { render :edit, status: :unprocessable_entity }
        
      end
    end
  end

  # DELETE /games/1
  def destroy
    @game.destroy
    puts "destroy"
    respond_to do |format|
      format.html { redirect_to games_url, notice: "Game was successfully destroyed." }
      
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def game_params
      params.require(:game).permit(:name, :condition, :min_player, :max_player, :price, :description, :genre)
    end

    def check_ownership
      if !(current_user.admin? or current_user.id == @game.user_id)
        redirect_to games_url, alert: "You have to be the seller of a game or an admin to do this."
      end
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/addresses/index.html.erb
<h1>Addresses Index</h1>

<% @addresses.each do |address| %>
    
    <p>
      <strong>Street:</strong>
      <%= address.street_number %> <%= address.street_name %>
    </p>

    <p>
      <strong>Suburb:</strong>
      <%= address.suburb %>
    </p>

    <p>
      <strong>State:</strong>
      <%= address.state %>
    </p>

    <p>
      <strong>Postcode:</strong>
      <%= address.postcode %>
    </p>
  
  <% end %>

app/views/addresses/new.html.erb
<h1>Add your address</h1>

<%= form_with model: @address do |form| %>
    <div class="field">
        <%= form.label :street_number %>
        <%= form.number_field :street_number, required:true %>
    </div>

    <div class="field">
        <%= form.label :street_name %>
        <%= form.text_field :street_name, required:true %>
    </div>

    <div class="field">
        <%= form.label :suburb %>
        <%= form.text_field :suburb, required:true %>
    </div>

    <div class="field">
        <%= form.label :state %>
        <%= form.text_field :state, required:true %>
    </div>

    <div class="field">
        <%= form.label :postcode %>
        <%= form.text_field :postcode, required:true %>
    </div>

    <div class="actions">
        <%= form.submit %>
    </div>
<% end %>

app/views/addresses/show.html.erb
<h1>Address of Username</h1>
<p>Street: <%= @address.street_number %> <%= @address.street_name %></p>
<p>Suburb: <%= @address.suburb %></p>
<p>Postcode: <%= @address.postcode %></p>
<p>State: <%= @address.state %></p>

app/views/games/_form.html.erb
<%= form_with(model: game) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :genre %><br>
    <%= form.select :genre, Game.genres.keys %>
  </div>

  <div class="field">
    <%= form.label :condition %><br>
    <%= form.select :condition, Game.conditions.keys %>
  </div>

  <div class="field">
    <%= form.label :min_player %><br>
    <%= form.number_field :min_player %>
  </div>

  <div class="field">
    <%= form.label :max_player %><br>
    <%= form.number_field :max_player %>
  </div>

  <div class="field">
    <%= form.label :price %><br>
    <%= form.text_field :price %>
  </div>


  <div class="field">
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Games</h1>

  <% @games.each do |game| %>
      
    <h3>
      <%= game.name %>
    </h3>

    <p>
      <strong>Genre:</strong>
      <%= game.genre %>
    </p>

    <p>
      <strong>Players:</strong>
      <%= game.min_player %> to <%= game.max_player %>
    </p>

    <p>
      <strong>Price:</strong>
      $<%= game.price %>
    </p>


    
    <p><%= link_to 'Show', game %></p>
  
  <% end %>
  

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @game.name %>
</p>

<p>
  <strong>Condition:</strong>
  <%= @game.condition %>
</p>

<p>
  <strong>Min player:</strong>
  <%= @game.min_player %>
</p>

<p>
  <strong>Max player:</strong>
  <%= @game.max_player %>
</p>

<p>
  <strong>Price:</strong>
  <%= @game.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @game.description %>
</p>

<p>
  <strong>Seller:</strong>
  <%= @game.user.username %>
</p>

<% if user_signed_in? and (current_user.admin? or current_user.id == @game.user_id) %>
  <%= link_to 'Edit', edit_game_path(@game) %> |
  <%= button_to 'Destroy', @game, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>
<%= link_to 'Back', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BoredGames</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p></p>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
                <li class="nav-item">
                    <%= link_to "Home", games_path, class: "nav-link active" %> 
                </li>
                
                <% if user_signed_in? %>
                    <li class="nav-item">
                        <%= link_to 'Sell my game', new_game_path, class: "nav-link active" %>
                    </li>

                    <li class="nav-item">
                        <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link active" %>
                    </li>
                <% else %>
                    <li class="nav-item">
                        <%= link_to "Sign in", new_user_session_path, class: "nav-link active" %>
                    </li>

                    <li class="nav-item">
                        <%= link_to "Sign up", new_user_registration_path, class: "nav-link active" %>
                    </li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>